SET
    FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE Contacts;

TRUNCATE TABLE Users;

SET
    FOREIGN_KEY_CHECKS = 1;

INSERT INTO
    Users (ID, Username, Password, Salt)
VALUES
    (
        'cd336184-fbc1-11f0-bb4f-0a0027000002',
        "charlie",
        "hashedPass1",
        "salt1"
    ),
    (
        'cd335cf2-fbc1-11f0-bb4f-0a0027000002',
        "bob",
        "hashedPass2",
        "salt2"
    ),
    (
        'cd3312e5-fbc1-11f0-bb4f-0a0027000002',
        "john",
        "hashedPass3",
        "salt3"
    );

-- Generated by Gemini Pro v3 and edited by database engineer
INSERT INTO
    Contacts (
        UserID,
        FirstName,
        LastName,
        Phone,
        Email,
        DateCreated
    )
VALUES
    -- expect data for column 'Email' to be too long.
    -- (
    --     'cd336184-fbc1-11f0-bb4f-0a0027000002',
    --     'Sarah',
    --     'Connor',
    --     '555-0101',
    --     'sarah.c@sky.net5555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555',
    --     CURRENT_TIMESTAMP
    -- ),
    (
        'cd336184-fbc1-11f0-bb4f-0a0027000002',
        'Sara',
        'Connor',
        '555-0101',
        'sarah.c@sky.net',
        CURRENT_TIMESTAMP
    ),
    (
        'cd336184-fbc1-11f0-bb4f-0a0027000002',
        'Sara',
        'Connor',
        '555-0101',
        'sarah.c@sky.net',
        CURRENT_TIMESTAMP
    ),
    (
        'cd336184-fbc1-11f0-bb4f-0a0027000002',
        'James',
        'Gordon',
        '555-0102',
        'jim.gordon@gcpd.gov',
        CURRENT_TIMESTAMP
    ),
    (
        'cd336184-fbc1-11f0-bb4f-0a0027000002',
        'Ellen',
        'Ripley',
        '555-0103',
        'ripley@nostromo.space',
        CURRENT_TIMESTAMP
    ),
    (
        'cd336184-fbc1-11f0-bb4f-0a0027000002',
        'Marty',
        'McFly',
        '555-0104',
        'marty@hillvalley.edu',
        CURRENT_TIMESTAMP
    ),
    (
        'cd336184-fbc1-11f0-bb4f-0a0027000002',
        'Dana',
        'Scully',
        '555-0105',
        'dana.scully@fbi.gov',
        CURRENT_TIMESTAMP
    ),
    (
        'cd335cf2-fbc1-11f0-bb4f-0a0027000002',
        'Fox',
        'Mulder',
        '555-0106',
        'fox.mulder@fbi.gov',
        CURRENT_TIMESTAMP
    ),
    (
        'cd335cf2-fbc1-11f0-bb4f-0a0027000002',
        'Fox',
        'Malder',
        '555-106',
        'fox.mulder@fbi.gov',
        CURRENT_TIMESTAMP
    ),
    (
        'cd335cf2-fbc1-11f0-bb4f-0a0027000002',
        'Walter',
        'White',
        '555-0107',
        'heisenberg@chem.org',
        CURRENT_TIMESTAMP
    ),
    (
        'cd335cf2-fbc1-11f0-bb4f-0a0027000002',
        'Jesse',
        'Pinkman',
        '555-0108',
        'jesse.p@abq.net',
        CURRENT_TIMESTAMP
    ),
    (
        'cd335cf2-fbc1-11f0-bb4f-0a0027000002',
        'Hermione',
        'Granger',
        '555-0109',
        'h.granger@ministry.magic',
        CURRENT_TIMESTAMP
    ),
    (
        'cd335cf2-fbc1-11f0-bb4f-0a0027000002',
        'Jon',
        'Snow',
        '555-0110',
        'jon.snow@wall.watch',
        CURRENT_TIMESTAMP
    ),
    (
        'cd3312e5-fbc1-11f0-bb4f-0a0027000002',
        'Arya',
        'Stark',
        '555-0111',
        'no.one@bravos.org',
        CURRENT_TIMESTAMP
    ),
    -- expect fail: foreign key violation
    -- ('', '', '', '', '', CURRENT_TIMESTAMP),
    -- expect fail: 'UserID' cannot be null
    -- (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
    (
        'cd3312e5-fbc1-11f0-bb4f-0a0027000002',
        'Tony',
        'Soprano',
        '555-0112',
        't.soprano@waste.mgt',
        CURRENT_TIMESTAMP
    ),
    (
        'cd3312e5-fbc1-11f0-bb4f-0a0027000002',
        'Leslie',
        'Knope',
        '555-0113',
        'leslie@pawnee.gov',
        CURRENT_TIMESTAMP
    ),
    (
        'cd3312e5-fbc1-11f0-bb4f-0a0027000002',
        'Ron',
        'Swanson',
        '555-0114',
        'ron@verygood.wood',
        CURRENT_TIMESTAMP
    ),
    (
        'cd3312e5-fbc1-11f0-bb4f-0a0027000002',
        'Michael',
        'Scott',
        '555-0115',
        'm.scott@paper.biz',
        CURRENT_TIMESTAMP
    );