INSERT INTO Users (ID, Username, Password)
VALUES 
    ('cd336184-fbc1-11f0-bb4f-0a0027000002', "charlie", "hashedPass1"),
    ('cd335cf2-fbc1-11f0-bb4f-0a0027000002', "bob", "hashedPass2"),
    ('cd3312e5-fbc1-11f0-bb4f-0a0027000002', "john", "hashedPass3");


-- Generated by an LLM
INSERT INTO Contacts (UserID, FirstName, LastName, Phone, Email, DateCreated)
VALUES
    ('cd336184-fbc1-11f0-bb4f-0a0027000002', 'Sarah', 'Connor', '555-0101', 'sarah.c@sky.net', NOW()),
    ('cd336184-fbc1-11f0-bb4f-0a0027000002', 'James', 'Gordon', '555-0102', 'jim.gordon@gcpd.gov', NOW()),
    ('cd336184-fbc1-11f0-bb4f-0a0027000002', 'Ellen', 'Ripley', '555-0103', 'ripley@nostromo.space', NOW()),
    ('cd336184-fbc1-11f0-bb4f-0a0027000002', 'Marty', 'McFly', '555-0104', 'marty@hillvalley.edu', NOW()),
    ('cd336184-fbc1-11f0-bb4f-0a0027000002', 'Dana', 'Scully', '555-0105', 'dana.scully@fbi.gov', NOW()),
    ('cd335cf2-fbc1-11f0-bb4f-0a0027000002', 'Fox', 'Mulder', '555-0106', 'fox.mulder@fbi.gov', NOW()),
    ('cd335cf2-fbc1-11f0-bb4f-0a0027000002', 'Walter', 'White', '555-0107', 'heisenberg@chem.org', NOW()),
    ('cd335cf2-fbc1-11f0-bb4f-0a0027000002', 'Jesse', 'Pinkman', '555-0108', 'jesse.p@abq.net', NOW()),
    ('cd335cf2-fbc1-11f0-bb4f-0a0027000002', 'Hermione', 'Granger', '555-0109', 'h.granger@ministry.magic', NOW()),
    ('cd335cf2-fbc1-11f0-bb4f-0a0027000002', 'Jon', 'Snow', '555-0110', 'jon.snow@wall.watch', NOW()),
    ('cd3312e5-fbc1-11f0-bb4f-0a0027000002', 'Arya', 'Stark', '555-0111', 'no.one@bravos.org', NOW()),
    ('cd3312e5-fbc1-11f0-bb4f-0a0027000002', 'Tony', 'Soprano', '555-0112', 't.soprano@waste.mgt', NOW()),
    ('cd3312e5-fbc1-11f0-bb4f-0a0027000002', 'Leslie', 'Knope', '555-0113', 'leslie@pawnee.gov', NOW()),
    ('cd3312e5-fbc1-11f0-bb4f-0a0027000002', 'Ron', 'Swanson', '555-0114', 'ron@verygood.wood', NOW()),
    ('cd3312e5-fbc1-11f0-bb4f-0a0027000002', 'Michael', 'Scott', '555-0115', 'm.scott@paper.biz', NOW());
